# Generated by Django 5.0.6 on 2024-10-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_administrador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('numero_celular', models.IntegerField()),
                ('run', models.CharField(max_length=12, unique=True)),
                ('numero_documento', models.IntegerField(unique=True)),
                ('foto_perfil', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero_tarjeta', models.IntegerField(primary_key=True, serialize=False)),
                ('CVV', models.IntegerField()),
                ('fecha_caducidad', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tarjeta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cita', models.CharField(max_length=100)),
                ('hora_cita', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.administrador')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.usuario')),
            ],
        ),
    ]
