# Generated by Django 5.0.6 on 2024-10-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_celular',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
    ]
