# Generated by Django 5.0.6 on 2024-10-21 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_suscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.tarjeta'),
        ),
    ]
