# Generated by Django 5.0.6 on 2024-11-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_suscripcion_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.medico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.usuario'),
        ),
    ]
